name: run-tests

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, zip, mbstring
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --testdox --no-progress
